services:
  tuvino:
    container_name: tuvino-api
    ports:
      - '8000:8000'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    env_file:
      - ./.env

  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - postgresql_db_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"

volumes:
  postgresql_db_data: