services:
  tuvino:
    container_name: tuvino-api
    ports:
      - '8000:8000'
    build:
      context: src
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./src:/src
