services:
  tuvino:
    container_name: tuvino-api
    ports:
      - '8000:8000'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    env_file:
      - ./.env