"""user_preferences_schema

Revision ID: fcf98ec788fb
Revises: b9a1eab37839
Create Date: 2025-07-11 20:08:56.588919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf98ec788fb'
down_revision: Union[str, Sequence[str], None] = 'b9a1eab37839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preference_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preference_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('option', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['preference_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('option_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['preference_options.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(
        sa.table('preference_categories',
            sa.Column('id', sa.Integer()),
            sa.Column('name', sa.String()),
            sa.Column('description', sa.String())
        ),
        [
            {'id': 1, 'name': 'types', 'description': 'Different types of wine'},
            {'id': 2, 'name': 'bodies', 'description': 'Wine body characteristics'},
            {'id': 3, 'name': 'intensities', 'description': 'Flavor intensity levels'},
            {'id': 4, 'name': 'dryness', 'description': 'Dryness levels'},
            {'id': 5, 'name': 'abv', 'description': 'Alcohol by volume'}
        ]
    )

    op.bulk_insert(
        sa.table('preference_options',
            sa.Column('category_id', sa.Integer()),
            sa.Column('option', sa.String()),
            sa.Column('description', sa.String()),
            sa.Column('value', sa.Float())
        ),
        [
            # Types (category_id = 1)
            {'category_id': 1, 'option': 'Tinto', 'description': 'Rico y profundo en sabor', 'value': 1.00},
            {'category_id': 1, 'option': 'Blanco', 'description': 'Ligero y refrescante', 'value': 0.01},
            {'category_id': 1, 'option': 'Rosado', 'description': 'Una combinación de características de vinos tintos y blancos', 'value': 0.50},
            {'category_id': 1, 'option': 'Espumoso', 'description': 'Burbujeante y festivo', 'value': 2.00},
            {'category_id': 1, 'option': 'No sabe/no contesta', 'description': None, 'value': None},

            # Bodies (category_id = 2)
            {'category_id': 2, 'option': 'Muy ligero', 'description': 'como un sorbo delicado sin mucha presencia', 'value': 0.01},
            {'category_id': 2, 'option': 'Ligero', 'description': 'con algo más de presencia que el agua', 'value': 0.25},
            {'category_id': 2, 'option': 'Medio', 'description': 'equilibrado y fácil de beber', 'value': 0.50},
            {'category_id': 2, 'option': 'Robusto', 'description': 'un vino con sustancia notable', 'value': 0.75},
            {'category_id': 2, 'option': 'De cuerpo completo',
             'description': 'intenso, robusto y con mucha presencia en el paladar', 'value': 1.00},
            {'category_id': 2, 'option': 'No sabe/no contesta', 'description': None, 'value': None},

            # Intensities (category_id = 3)
            {'category_id': 3, 'option': 'Muy sutil', 'description': 'una insinuación apenas perceptible del sabor', 'value': '0.01'},
            {'category_id': 3, 'option': 'Suave', 'description': 'presente sin llegar a ser abrumador', 'value': 0.25},
            {'category_id': 3, 'option': 'Equilibrada',
             'description': 'una buena mezcla de sabores que se hacen notar de manera constante', 'value': 0.50},
            {'category_id': 3, 'option': 'Intensa', 'description': 'los sabores se destacan con claridad', 'value': 0.75},
            {'category_id': 3, 'option': 'Muy intensa', 'description': 'una explosión de sabor en cada sorbo', 'value': 1.00},
            {'category_id': 3, 'option': 'No sabe/no contesta', 'description': None, 'value': None},

            # Dryness (category_id = 4)
            {'category_id': 4, 'option': 'Muy suave', 'description': 'sin sensación alguna de sequedad', 'value': 0.01},
            {'category_id': 4, 'option': 'Mayormente suave', 'description': 'con un leve toque de sequedad', 'value': 0.25},
            {'category_id': 4, 'option': 'Con una textura moderada',
             'description': 'equilibrado, entre suavidad y un toque de sequedad', 'value': 0.50},
            {'category_id': 4, 'option': 'Con textura marcada', 'description': 'se nota algo de sequedad en la lengua', 'value': 0.75},
            {'category_id': 4, 'option': 'Con fuerte textura',
             'description': 'una sensación de sequedad pronunciada que le da estructura al vino', 'value': 1.00},
            {'category_id': 4, 'option': 'No sabe/no contesta', 'description': None, 'value': None},

            # ABV (category_id = 5)
            {'category_id': 5, 'option': 'Suave', 'description': None, 'value': 11.0},
            {'category_id': 5, 'option': 'Moderado', 'description': None, 'value': 12.25},
            {'category_id': 5, 'option': 'Alto contenido alcohólico', 'description': None, 'value': 13.5},
            {'category_id': 5, 'option': 'No sabe/no contesta', 'description': None, 'value': None}
        ]
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preferences')
    op.drop_table('preference_options')
    op.drop_table('preference_categories')
    # ### end Alembic commands ###
