"""add_reviews_and_summary

Revision ID: 7aa0c7a521c0
Revises: 3e8a11d4b6da
Create Date: 2025-10-17 23:15:36.681499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aa0c7a521c0'
down_revision: Union[str, Sequence[str], None] = '3e8a11d4b6da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wine_ratings', sa.Column('review', sa.String(), nullable=True))
    op.add_column('wines', sa.Column('summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wines', 'summary')
    op.drop_column('wine_ratings', 'review')
    # ### end Alembic commands ###
