"""create_wines_table

Revision ID: 39ed92195d36
Revises: 8198f8e987b5
Create Date: 2025-09-11 18:14:04.217643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pathlib import Path

# revision identifiers, used by Alembic.
revision: str = '39ed92195d36'
down_revision: Union[str, Sequence[str], None] = '8198f8e987b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wines',
    sa.Column('wine_id', sa.Integer(), nullable=False),
    sa.Column('wine_name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('elaborate', sa.String(), nullable=True),
    sa.Column('grapes', sa.String(), nullable=True),
    sa.Column('harmonize', sa.String(), nullable=True),
    sa.Column('abv', sa.Float(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('acidity', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('winery', sa.String(), nullable=True),
    sa.Column('vintages', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('wine_id')
    )
    # ### end Alembic commands ###
    sql_file_path = Path(__file__).parent.parent / 'data' / '202509111534_wines.sql'

    with open(sql_file_path, 'r', encoding='utf-8') as sql_file:
        sql_content = sql_file.read()

    op.execute(sql_content)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wines')
    # ### end Alembic commands ###
