"""translate_harmonize

Revision ID: 76e360dc1524
Revises: 7aa0c7a521c0
Create Date: 2025-10-27 02:10:30.473360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pathlib import Path


# revision identifiers, used by Alembic.
revision: str = '76e360dc1524'
down_revision: Union[str, Sequence[str], None] = '7aa0c7a521c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('wines', sa.Column('harmonize_es', sa.String(), nullable=True))

    sql_file_path = Path(__file__).parent.parent / 'data' / '202510262300_translate_harmonize.sql'

    with open(sql_file_path, 'r', encoding='utf-8') as sql_file:
        sql_content = sql_file.read()

    op.execute(sql_content)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wines', 'harmonize_es')
    # ### end Alembic commands ###
